import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local"; // Import localFont
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Définition des polices locales
const interLocal = localFont({
  src: "../../public/fonts/Inter-VariableFont.ttf",
  variable: "--font-inter",
  display: "swap",
});

const jetbrainsMonoLocal = localFont({
  src: "../../public/fonts/JetBrainsMono-VariableFont.ttf",
  variable: "--font-jetbrains-mono",
  display: "swap",
});

const wfVisualSans = localFont({
  src: "../../public/fonts/WFVisualSans-Regular.ttf",
  variable: "--font-wf-visual-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${interLocal.variable} ${jetbrainsMonoLocal.variable} ${wfVisualSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}